### ISSUE TITLE
Error building sinsynth

### ISSUE THREAD

**Issue by yphil-dev** [harryhaaren/lv2#1]
(...)
[33/44] c: plugins/eg-sinsynth.lv2/sinsynth.c -> build/plugins/eg-sinsynth.lv2/sinsynth.c.3.o
[34/44] cxx: plugins/eg-sinsynth.lv2/widget.cpp -> build/plugins/eg-sinsynth.lv2/widget.cpp.4.o
In file included from ../plugins/eg-sinsynth.lv2/widget.cpp:4:0:
../plugins/eg-sinsynth.lv2/widget.h:5:19: fatal error: FL/Fl.H: No such file or directory
 #include <FL/Fl.H>
                   ^
compilation terminated.
[35/44] cxx: plugins/eg-sinsynth.lv2/sinsynth_gui.cpp -> build/plugins/eg-sinsynth.lv2/sinsynth_gui.cpp.4.o
../plugins/eg-sinsynth.lv2/sinsynth_gui.cpp:10:18: fatal error: FL/x.H: No such file or directory
 #include <FL/x.H>
                  ^
compilation terminated.

**Comment by rlbossman** [comment]
You are missing http://fltk.org/pub/fltk/1.3.2/fltk-1.3.2-source.tar.gz

**Comment by harryhaaren** [comment]
Hi @xaccrocheur, You are missing a library: NTK. I've just pushed commit  dd6df355e06f61a4723321fe30724609a0560726 which adds a "mandatory" check for the library.

If your distro packages NTK, it should be available as `ntk` or perhaps `libntk` (and possibly `libntk-dev`). Otherwise grab it from here, and build: http://non.tuxfamily.org/wiki/NTK

@rlbossman, although the error does reference FLTK, NTK has newer X-Embed code, so I'm not sure it'll compile ( & run proplerly! ) on FLTK.

Closing, Cheers, -Harry

**Comment by yphil-dev** [comment]
Hi Harry! OK, it builds now, but only from its own dir, from the repo root it still says 

```
Configuration failed, eg-sinsynth.lv2 will not be built
```

(Why is waf so absurdly complex? I'm still trying to understand the mere logic of it)
The plugin works, but the UI window has no titlebar, does not stay on screen (Unity DE / Qtractor SVN) and it makes jalv.gtk\* coredump.

It seems that the freq value is not sync between the generic UI and the NTK UI. 
I wonder how hard it would be to add MIDI control and note on / off ;)

Thanks for the help, Bbye -xacc
